name: weatherapp-debug

services:
  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

  ingestion:
    build: ./ingestion
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  dbdata:
